name: Production Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Prod
        run: |
          echo "staging test done"
          echo "deploy running."
